DROP DATABASE IF EXISTS DBEX06;
CREATE DATABASE DBEX06;
USE DBEX06;
CREATE TABLE ALUNO(
	IDALUNO INT NOT NULL auto_increment,
    NOME varchar(100),
    DT_NASCIMENTO DATE,
    TELEFONE_CELULAR varchar(11),
    TELEFONE_RESIDENCIAL VARCHAR(11),
    TELEFONE_CONTATO_NOME VARCHAR(100),
    TELEFONE_CONTATO_NUMERO VARCHAR(11),
    PRIMARY KEY (IDALUNO)
);