CREATE DATABASE IF NOT EXISTS EXERCICIO11;
USE EXERCICIO11;

CREATE TABLE TITULAR(
IDTITULAR INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45),
CPF VARCHAR(11),
PRIMARY KEY (IDTITULAR)
);

CREATE TABLE DEPENDENTE(
IDDEPENDENTE INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45),
DTNASC DATE,
IDTITULAR INT NOT NULL,
PRIMARY KEY(IDDEPENDENTE),
FOREIGN KEY(IDTITULAR)REFERENCES TITULAR
);

