SET GLOBAL log_bin_trust_function_creators = 1;
DROP DATABASE IF EXISTS DBVACINA;
CREATE DATABASE DBVACINA;
USE DBVACINA;

CREATE TABLE COMPRA (
	IDCOMPRA INT NOT NULL AUTO_INCREMENT
    , DTCOMPRA DATE
    , LOTE CHAR(15)
    , QTDE INT
    , INTERVALO INT
    , PRIMARY KEY (IDCOMPRA)
);

CREATE TABLE PACIENTE (
	IDPACIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , DTATENDIMENTO DATE
    , PRIMARY KEY (IDPACIENTE)
);

CREATE TABLE VACINA (
	IDVACINA INT NOT NULL AUTO_INCREMENT
    , IDCOMPRA INT NOT NULL
    , REGISTRO CHAR(25)
    , IDPACIENTE INT
    , DTAPLICACAO DATE
    , DOSE INT
    , PRIMARY KEY (IDVACINA)
    , FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA (IDCOMPRA)
    , FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (IDPACIENTE)
);

DELIMITER $$
create procedure sp_registra_compra(pQTDE int, pINTERVALO int)
begin 
DECLARE vANO CHAR(4);
    DECLARE vMES CHAR(2);
    DECLARE vDIA CHAR(2);
    declare vidcompra int;
    declare vcontador int;
    declare vlote_registro varchar(30);

	 SET vANO = YEAR(NOW());
    SET vMES = LPAD(MONTH(NOW()), 2, '0');
    SET vDIA = LPAD(DAY(NOW()), 2, '0');
    
    insert into compra (dtcompra, qtde, intervalo)values(now(), pqtde, pintervalo);
    set vidcompra = last_insert_id();
    
    update compra
    set vlote_registro = concat(concat(concat(vano,vmes), vdia), lpad(vcompra,7,'0'))
    where idcompra = vidcompra;
    
    set vcontador =1
    while (vcontador <= pqtde) do
    insert into vacina(idcompra, registro) values(vidcompra, concat(vlote_registro, lpad(vcontador, 10, '0')));
    set vcontador = vcontador +1;
    end while;

end $



CREATE TRIGGER TR_BI_COMPRA BEFORE INSERT ON COMPRA FOR EACH ROW
BEGIN
	/*QUESTAO 1*/
	DECLARE vANO CHAR(4);
    DECLARE vMES CHAR(2);
    DECLARE vDIA CHAR(2);
    DECLARE vID  CHAR(7);
    
	-- CALCULANDO O LOTE
    SET vANO = YEAR(NOW());
    SET vMES = LPAD(MONTH(NOW()), 2, '0');
    SET vDIA = LPAD(DAY(NOW()), 2, '0');
    
	SELECT LPAD(AUTO_INCREMENT, 7, '0') 
    INTO vID
	FROM information_schema.tables 
	WHERE TABLE_SCHEMA = 'DBVACINA' AND TABLE_NAME = 'COMPRA';   
    
    

	SET NEW.DTCOMPRA = NOW();
    SET NEW.LOTE = CONCAT(CONCAT(CONCAT(vANO, vMES),vDIA), vID);
        
END $$

CREATE TRIGGER TR_AI_COMPRA AFTER INSERT ON COMPRA FOR EACH ROW
BEGIN
	/*QUESTAO 2*/
	DECLARE vQTDE INT;
    DECLARE vREGISTRO CHAR(25);
    
	SET vQTDE = 1;
	WHILE vQTDE <= NEW.QTDE DO
		
		/*QUESTAO 3*/
        SET vREGISTRO = CONCAT(NEW.LOTE, LPAD(vQTDE, 10, '0'));
      
		INSERT INTO VACINA(IDCOMPRA, REGISTRO)VALUES(NEW.IDCOMPRA, vREGISTRO); 
		SET vQTDE = vQTDE + 1; 
       
	END WHILE;

END $$

CREATE TRIGGER TR_AF_PACIENTE AFTER INSERT ON PACIENTE FOR EACH ROW
BEGIN

	DECLARE vIDVACINA_1DOSE INT;
    DECLARE vIDVACINA_2DOSE INT;
    DECLARE vINTERVALO INT;
    
    -- PEGANDO A 1 DOSE
	SELECT MIN(IDVACINA) 
	INTO vIDVACINA_1DOSE
	FROM VACINA WHERE IDPACIENTE IS NULL;

	UPDATE VACINA SET 
		IDPACIENTE = NEW.IDPACIENTE
        , DTAPLICACAO = NOW() 
        , DOSE = 1
	WHERE IDVACINA = vIDVACINA_1DOSE;

	-- PEGANDO O INTERVALO
    SELECT COMPRA.INTERVALO 
    INTO vINTERVALO
	FROM
		VACINA
		INNER JOIN COMPRA ON
		COMPRA.IDCOMPRA = VACINA.IDCOMPRA
	WHERE VACINA.IDVACINA = vIDVACINA_1DOSE;

    -- PEGANDO A 2 DOSE
	SELECT MIN(IDVACINA) 
	INTO vIDVACINA_2DOSE
	FROM VACINA WHERE IDPACIENTE IS NULL;

	UPDATE VACINA SET 
		IDPACIENTE = NEW.IDPACIENTE
        , DTAPLICACAO = DATE_ADD(NOW(), INTERVAL vINTERVALO DAY)
        , DOSE = 2
	WHERE IDVACINA = vIDVACINA_2DOSE;
    
END $$

DELIMITER ;


INSERT INTO COMPRA (QTDE, INTERVALO)VALUES(5, 10);
INSERT INTO COMPRA (QTDE, INTERVALO)VALUES(2, 15);
SELECT * FROM COMPRA;
SELECT * FROM VACINA;
SELECT * FROM PACIENTE;

INSERT INTO PACIENTE(NOME)VALUES('ANDRE');