DROP DATABASE IF EXISTS DBEXERCICIO8;

CREATE DATABASE DBEXERCICIO8;

USE DBEXERCICIO8;

CREATE TABLE VEICULO_DOCUMENTO (
IDVEICULO		INT	NOT NULL,
MODELO			VARCHAR(45),
PLACA			VARCHAR(8),
YRFABRICACAO	INT,
MARCA			VARCHAR(45),
IDDOCUMENTO		INT NOT NULL,
RENAVAN			INT,
UFREGISTRO		CHAR(2),
DTREGISTRO		DATE,
CIDADEREGISTRO	VARCHAR(45),
PRIMARY KEY(IDVEICULO, IDDOCUMENTO)
);