-- MySQL Script generated by MySQL Workbench
-- Mon Nov 30 11:56:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EX.3_CARRO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EX.3_CARRO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EX.3_CARRO` DEFAULT CHARACTER SET utf8 ;
USE `EX.3_CARRO` ;

-- -----------------------------------------------------
-- Table `EX.3_CARRO`.`CARRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EX.3_CARRO`.`CARRO` (
  `IDCARRO` INT NOT NULL,
  `MARCA` VARCHAR(45) NULL,
  `MODELO` VARCHAR(45) NULL,
  `ANO_MODELO` YEAR(4) NULL,
  `ANO_FABRICACAO` YEAR(4) NULL,
  `COR` VARCHAR(45) NULL,
  `PLACA` VARCHAR(45) NULL,
  `CHASSI` VARCHAR(45) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
