-- MySQL Script generated by MySQL Workbench
-- Mon Nov 30 12:03:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EX.2_USUARIO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EX.2_USUARIO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EX.2_USUARIO` DEFAULT CHARACTER SET utf8 ;
USE `EX.2_USUARIO` ;

-- -----------------------------------------------------
-- Table `EX.2_USUARIO`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EX.2_USUARIO`.`USUARIO` (
  `IDUSUARIO` INT NOT NULL,
  `NOME` VARCHAR(45) NULL,
  `LOGIN` VARCHAR(45) NULL,
  `SENHA` VARCHAR(45) NULL,
  `DT_NASCIMENTO` DATE NULL,
  `GENERO` CHAR(1) NULL,
  PRIMARY KEY (`IDUSUARIO`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
