CREATE DATABASE IF NOT EXISTS EXERCICIO13;
USE EXERCICIO13;
CREATE TABLE CRIMINOSO(
IDCRIMINOSO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45),
CPF INT,
PRIMARY KEY(IDCRIMINOSO)
);
CREATE TABLE VITIMA(
IDVITIMA INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45),
CPF INT,
PRIMARY KEY(IDVITIMA)
);
CREATE TABLE ARMA(
IDARMA INT NOT NULL AUTO_INCREMENT,
TIPO VARCHAR(20),
DESCRICAO TEXT,
PRIMARY KEY (IDARMA)
);
CREATE TABLE CRIME(
IDCRIME INT NOT NULL AUTO_INCREMENT,
DT_OCORRIDO DATE,
TIPO VARCHAR(45),
PRIMARY KEY (IDCRIME)
);

CREATE TABLE ATACAR(
IDATACAR INT NOT NULL AUTO_INCREMENT,
IDCRIMINOSO INT NOT NULL,
IDVITIMA INT NOT NULL,
PRIMARY KEY (IDATACAR),
FOREIGN KEY(IDCRIMINOSO) REFERENCES CRIMINOSO,
FOREIGN KEY (IDVITIMA)  REFERENCES VITIMA 
);
CREATE TABLE COMETER(
IDCOMETER INT NOT NULL AUTO_INCREMENT,
IDCRIMINOSO INT NOT NULL,
IDCRIME INT NOT NULL,
PRIMARY KEY(IDCOMETER),
FOREIGN KEY(IDCRIMINOSO) REFERENCES CRIMINOSO,
FOREIGN KEY(IDCRIME) REFERENCES CRIME
);
CREATE TABLE SOFRER(
IDSOFRER INT NOT NULL AUTO_INCREMENT,
IDVITIMA INT NOT NULL,
IDCRIME INT NOT NULL,
PRIMARY KEY (IDSOFRER),
FOREIGN KEY(IDVITIMA) REFERENCES VITIMA,
FOREIGN KEY(IDCRIME) REFERENCES CRIME
);

CREATE TABLE USAR(
IDUSAR INT NOT NULL AUTO_INCREMENT,
IDARMA INT NOT NULL,
IDCRIME INT NOT NULL,
PRIMARY KEY (IDUSAR),
FOREIGN KEY(IDARMA) REFERENCES ARMA,
FOREIGN KEY (IDCRIME) REFERENCES CRIME
);
