drop database if exists EXERCICIO10;

CREATE DATABASE EXERCICIO10;

USE EXERCICIO10;

CREATE TABLE USUARIO(
IDUSUARIO	INT NOT NULL AUTO_INCREMENT,
NOME		VARCHAR(45),
LOGIN		VARCHAR(15),
SENHA		VARCHAR(45),
DT_CADASTRO	DATE,
PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE VIDEO(
IDVIDEO		INT NOT NULL AUTO_INCREMENT,
TITULO		VARCHAR(45),
CATEGORIA 	VARCHAR(45),
DT_PUBLICACAO	DATE,
PRIMARY KEY(IDVIDEO)
);

CREATE TABLE ASSISTIR (
IDUSUARIO	INT	NOT NULL,
IDVIDEO		INT NOT NULL,
PRIMARY KEY	(IDUSUARIO, IDVIDEO),
FOREIGN KEY(IDUSUARIO)REFERENCES USUARIO(IDUSUARIO),
FOREIGN KEY(IDVIDEO)REFERENCES VIDEO(IDVIDEO)
);