CREATE DATABASE IF NOT EXISTS EXERCICIO12;
USE EXERCICIO12;

CREATE TABLE MEDICO(
IDMEDICO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45),
CRM VARCHAR(15),
CELULAR INT,
PRIMARY KEY(IDMEDICO)
);

CREATE TABLE PACIENTE(
IDPACIENTE INT NOT NULL AUTO_INCREMENT,
RUA VARCHAR(45),
NUMERO INT,
CIDADE VARCHAR(45),
CEP INT,
BAIRRO VARCHAR(45),
ESTADO CHAR(2),
PRIMARY KEY (IDPACIENTE)
);

CREATE TABLE CONSULTA(
IDCONSULTA INT NOT NULL AUTO_INCREMENT,
DIA DATE,
HORA TIME,
IDMEDICO INT NOT NULL,
IDPACIENTE INT NOT NULL,
PRIMARY KEY(IDCONSULTA),
FOREIGN KEY (IDMEDICO) REFERENCES MEDICO,
FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE
);
