DROP DATABASE IF EXISTS DBEXERCICIO7;

CREATE DATABASE DBEXERCICIO7;

USE DBEXERCICIO7;

CREATE TABLE COMPUTADOR(
IDCOMPUTADOR	INT NOT NULL AUTO_INCREMENT,
MARCA		VARCHAR(45),
MODELO		VARCHAR(45),
PRIMARY KEY(IDCOMPUTADOR)
);

CREATE TABLE CHAMADO(
IDCHAMADO	INT NOT NULL AUTO_INCREMENT,
HRCHAMADO	TIME,
DTCHAMADO	DATE,
DESCRICAO	VARCHAR(450),
IDCOMPUTADOR INT,
PRIMARY KEY(IDCHAMADO),
FOREIGN KEY(IDCHAMADO)REFERENCES COMPUTADOR(IDCOMPUTADOR)
);