drop database if exists DBEXERCICIO9;

create database DBEXERCICIO9;

use DBEXERCICIO9;

CREATE TABLE PRODUTO(
IDPRODUTO	INT NOT NULL AUTO_INCREMENT,
NOME		VARCHAR(45),
PRECO		INT,
PRIMARY KEY (IDPRODUTO)
);

CREATE TABLE PEDIDO(
IDPEDIDO	INT NOT NULL AUTO_INCREMENT,
HORA		TIME,
DT_PEDIDO	DATE,
PRIMARY KEY (IDPEDIDO)
);

CREATE TABLE PEDIDO_PRODUTO(
IDPRODUTO	INT NOT NULL,
IDPEDIDO	INT NOT NULL,
FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO),
FOREIGN KEY (IDPEDIDO) REFERENCES PEDIDO(IDPEDIDO)
);