DROP DATABASE IF EXISTS DBEX05;
CREATE DATABASE DBEX05;
USE DBEX05;
CREATE TABLE ALUNO(
	IDALUNO INT NOT NULL auto_increment,
    NOME VARCHAR(100) NOT NULL,
    IDADE INT,
    ENDERECO_LUGRADOURO varchar(150),
    NUMERO INT,
    BAIRRO varchar(100),
    CIDADE varchar(100),
    ESTADO CHAR(2),
    CEP varchar(15) NOT NULL,
    COMPLEMENTOS VARCHAR(150),
    PRIMARY KEY (IDALUNO)
);