-- MySQL Script generated by MySQL Workbench
-- Mon Nov 30 11:55:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EX.4_LIVRO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EX.4_LIVRO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EX.4_LIVRO` DEFAULT CHARACTER SET utf8 ;
USE `EX.4_LIVRO` ;

-- -----------------------------------------------------
-- Table `EX.4_LIVRO`.`LIVRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EX.4_LIVRO`.`LIVRO` (
  `IDLIVRO` INT NOT NULL,
  `TITULO` VARCHAR(45) NULL,
  `AUTOR` VARCHAR(45) NULL,
  `EDITORA` VARCHAR(45) NULL,
  `ANO_PUBLILCACAO` YEAR(4) NULL,
  PRIMARY KEY (`IDLIVRO`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
