DROP DATABASE IF EXISTS DBELEICAO;
CREATE DATABASE DBELEICAO;
USE DBELEICAO;
CREATE TABLE PARTIDO(
IDPARTIDO INT PRIMARY KEY,
NOME VARCHAR(255),
SIGLA VARCHAR(10)
);
CREATE TABLE CANDIDATO(
IDCANDIDADTO INT NOT NULL,
IDPARTIDO INT,
NOME VARCHAR(255),
RUA VARCHAR(100),
CEP VARCHAR(8),
CIDADE VARCHAR(100),
ESTADO CHAR(2),
FOREIGN KEY (IDPARTIDO) REFERENCES PARTIDO(IDPARTIDO)
);
CREATE TABLE FUNCIONARIO (
FUNCIONARIO INT PRIMARY KEY,
IDPARTIDO INT NOT NULL,

DESCRICAO VARCHAR (100)
);
CREATE TABLE USUARIO (
LOGIN VARCHAR(100),
SENHA VARCHAR(255),
EMAIL VARCHAR(100)
);
CREATE TABLE SETOR(
IDSETOR INT NOT NULL,
NOME VARCHAR(100)
);
CREATE TABLE FUNCAO(
DESCRICAO VARCHAR(100)
);
CREATE TABLE PARTICIPA(
IDFUNCAO INT,
IDUSUARIO INT
);
CREATE TABLE VOTAR(
IDELEICAO INT PRIMARY KEY,
IDUSUARIO INT,
IDCANDIDATO INT,
DT_VOTO DATETIME
);
CREATE TABLE ELEICAO (
IDELEICAO INT NOT NULL,
TITULO VARCHAR(100),
DT_INICIO DATETIME,
DT_FIM DATETIME,
PRIMARY KEY (IDELEICAO));

DROP TABLE 
CANDIDATO,
USUARIO;

ALTER TABLE FUNCIONARIO 
ADD NOME VARCHAR(100),
ADD CPF CHAR(11),
ADD SENHA VARCHAR(45);

ALTER TABLE FUNCIONARIO 
DROP FUNCIONARIO,
DROP IDPARTIDO,
DROP DESCRICAO;

ALTER TABLE FUNCIONARIO ADD IDFUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY;

RENAME TABLE SETOR TO DEPARTAMENTO;
ALTER TABLE DEPARTAMENTO DROP IDSETOR;
ALTER TABLE DEPARTAMENTO ADD IDDEPARTAMENTO INT auto_increment PRIMARY KEY;

RENAME TABLE FUNCAO TO CARGO;
ALTER TABLE CARGO ADD IDCARGO INT auto_increment PRIMARY KEY;

RENAME TABLE PARTIDO TO CHAPA;
ALTER TABLE CHAPA DROP IDPARTIDO, DROP SIGLA;
ALTER TABLE CHAPA 
ADD IDCHAPA INT auto_increment PRIMARY KEY,
ADD IDELEICAO INT NOT NULL,
ADD foreign key (IDELEICAO) REFERENCES ELEICAO (IDELEICAO);

ALTER TABLE CHAPA DROP NOME, ADD NOME VARCHAR(100);

ALTER TABLE VOTAR 
DROP IDELEICAO,
DROP IDUSUARIO,
DROP IDCANDIDATO;

ALTER TABLE VOTAR 
ADD IDELEICAO INT NOT NULL,
ADD IDFUNCIONARIO INT NOT NULL,
ADD IDCHAPA INT NOT NULL,
ADD PRIMARY KEY (IDELEICAO, IDFUNCIONARIO),
ADD FOREIGN KEY (IDELEICAO) REFERENCES ELEICAO (IDELEICAO),
ADD FOREIGN KEY (IDFUNCIONARIO) REFERENCES FUNCIONARIO (IDFUNCIONARIO),
ADD FOREIGN KEY (IDCHAPA) REFERENCES CHAPA (IDCHAPA);

ALTER TABLE VOTAR DROP DT_VOTO,
ADD DT_VOTO INT;

ALTER TABLE PARTICIPA 
ADD IDFUNCIONARIO INT NOT NULL,
ADD IDCHAPA INT NOT NULL,
ADD IDCARGO INT NOT NULL;


ALTER TABLE PARTICIPA
DROP IDFUNCAO,
DROP IDUSUARIO;

ALTER TABLE PARTICIPA
ADD PRIMARY KEY (IDFUNCIONARIO, IDCHAPA),
ADD foreign key (IDFUNCIONARIO) REFERENCES FUNCIONARIO (IDFUNCIONARIO),
ADD foreign key (IDCHAPA) REFERENCES CHAPA (IDCHAPA),
ADD foreign key (IDCARGO) REFERENCES CARGO (IDCARGO);

ALTER TABLE FUNCIONARIO ADD IDDEPARTAMENTO INT NOT NULL,
ADD foreign key (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO (IDDEPARTAMENTO);
