DROP DATABASE IF EXISTS DBDELEGACIA;

CREATE DATABASE DBDELEGACIA;

USE DBDELEGACIA;

CREATE TABLE CRIME (
	IDCRIME INT NOT NULL,
	DESCRICAO VARCHAR(255),
	RUA VARCHAR(100),
	NUMERO INT,
	COMPLEMENTO VARCHAR(255),
	BAIRRO VARCHAR(100),
	CEP VARCHAR(8),
	CIDADE VARCHAR(100),
	ESTADO CHAR(2)
);

ALTER TABLE CRIME ADD PRIMARY KEY (IDCRIME);
ALTER TABLE CRIME ADD DTCRIME DATE;

CREATE TABLE CRIMINOSO(
  RUA VARCHAR(100),
  NUMERO INT,
  COMPLEMENTO VARCHAR(255),
  BAIRRO VARCHAR(100),
  CEP CHAR(8),
  CIDADE VARCHAR(100),
  ESTADO CHAR(2),
  DTNASCIMENTO DATE,
  TELEFONE VARCHAR(15)
);

ALTER TABLE CRIMINOSO ADD IDCRIMINOSO INT NOT NULL PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE CRIMINOSO ADD NOME VARCHAR(45);


CREATE TABLE OCORRENCIA (
	IDOCORRENCIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DT_OCORRENCIA DATE
);

CREATE TABLE ITEM_OCORRENCIA (
	IDITEM INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDOCORRENCIA INT NOT NULL,
	DESCRICAO VARCHAR (100),
	CONSTRAINT FK_ITEM_OCORRENCIA_OCORRENCIA FOREIGN KEY (IDOCORRENCIA) REFERENCES OCORRENCIA(IDOCORRENCIA)
);

DROP TABLE ITEM_OCORRENCIA; 
DROP TABLE OCORRENCIA; 

CREATE TABLE VITIMA (
  RUA VARCHAR(100),
  NUMERO INT,
  COMPLEMENTO VARCHAR(255),
  BAIRRO VARCHAR(100),
  CEP VARCHAR(8),
  CIDADE VARCHAR(100),
  ESTADO CHAR(2),
  DTNASCIMENTO DATE
);

ALTER TABLE VITIMA ADD IDVITIMA INT NOT NULL;
ALTER TABLE VITIMA ADD PRIMARY KEY (IDVITIMA);
ALTER TABLE VITIMA ADD NOME VARCHAR(45);

CREATE TABLE COMETE(
	IDCRIME INT NOT NULL,
	IDCRIMINOSO INT NOT NULL
);
ALTER TABLE COMETE ADD FOREIGN KEY (IDCRIME) REFERENCES CRIME(IDCRIME);
ALTER TABLE COMETE ADD FOREIGN KEY (IDCRIMINOSO) REFERENCES CRIMINOSO(IDCRIMINOSO);

CREATE TABLE ATACA (
	OBSERVACAO CHAR(1)
);

ALTER TABLE ATACA ADD IDVITIMA INT NOT NULL;
ALTER TABLE ATACA ADD IDCRIMINOSO INT NOT NULL;
ALTER TABLE ATACA ADD FOREIGN KEY (IDVITIMA) REFERENCES VITIMA(IDVITIMA);
ALTER TABLE ATACA ADD FOREIGN KEY (IDCRIMINOSO) REFERENCES CRIMINOSO(IDCRIMINOSO);
ALTER TABLE ATACA DROP OBSERVACAO;

CREATE TABLE SOFRE (
	IDCRIME INT NOT NULL,
	IDVITIMA INT NOT NULL
);

ALTER TABLE SOFRE ADD FOREIGN KEY (IDCRIME) REFERENCES CRIME(IDCRIME);
ALTER TABLE SOFRE ADD FOREIGN KEY (IDVITIMA) REFERENCES VITIMA(IDVITIMA);

CREATE TABLE ARMA (
	IDARMA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	MARCA VARCHAR(110)
);

ALTER TABLE ARMA DROP MARCA;
ALTER TABLE ARMA ADD DESCRICAO VARCHAR(45);
ALTER TABLE ARMA ADD TIPO ENUM("ARMA_BRANCA", "ARMA_DE_FOGO");

CREATE TABLE USADA (
	IDARMA INT NOT NULL,
	IDCRIME INT NOT NULL
);

ALTER TABLE USADA ADD FOREIGN KEY (IDARMA) REFERENCES ARMA(IDARMA);
ALTER TABLE USADA ADD FOREIGN KEY (IDCRIME) REFERENCES CRIME(IDCRIME);